### ISSUE TITLE
报错：java: 找不到符号   符号:   类 UserIp   位置: 程序包 com.cershy.linyuserver.annotation     

### ISSUE THREAD

**Issue by Bucengfeijianqurentou** [DWHengr/linyu-server#7]
![PixPin_2024-11-12_15-32-38](https://github.com/user-attachments/assets/2fe46064-e49c-4176-90fd-9c4a38850679)
![PixPin_2024-11-12_15-32-27](https://github.com/user-attachments/assets/4a0927e1-2bdb-46a3-bf82-a5e4d20b288f)

**Comment by Bucengfeijianqurentou** [comment]
annotation包下无UserIp类

**Comment by DWHengr** [comment]
更新一下代码。

**Comment by Bucengfeijianqurentou** [comment]
谢谢，问题解决
